### ISSUE TITLE
`` hurts again

### ISSUE THREAD

**Issue by subhashgada** [Staples-Inc/mqe-datasource#4]
when we use functions `` are encoded all the way to the end of the query instead  of just metric ID

**Comment by subhashgada** [comment]
Add another toggle like how app and hosts are selected for function to differentiate the metric id from the rest of the query.

**Comment by alexanderzobnin** [comment]
I think I need to implement functions editor like in Graphite datasource.

**Comment by SeemaKumaran** [comment]
Done.
