### ISSUE TITLE
issue with Alias

### ISSUE THREAD

**Issue by SeemaKumaran** [Staples-Inc/mqe-datasource#6]
While using metrics containing wildcards, for metrics like tag1.tag2.tag3.tag4.tag5.tag6, it returns the lengthy name includes the group identification which may not necessary to display in graph. 

For wildcard metrics, to choose the meaningful name or remove the unnecessary fields, need an index based aliasing. 

For example, the metric query is tag1.tag2.\* and for the metric tag1.tag2.tag3.tag4.tag5.tag6, need to display only last field say tag6 in the graph, use $6, so that it can display the same. If it is $5$6 in alias field, it will be tag5.tag6.

**Comment by alexanderzobnin** [comment]
Can you use `tag1.tag2.tag3.tag4.*` for querying tag5.tag6?

**Comment by SeemaKumaran** [comment]
Yes, it can be used. But this change is to take and display the meaningful name in the graph.

**Comment by SeemaKumaran** [comment]
Done
